### ISSUE TITLE
"spidey v" command not working 💔 

### ISSUE THREAD

**Issue by Reckadon** [glappy-py/spideycli#1]
![image](https://user-images.githubusercontent.com/69901221/141272526-bcc5d646-4d60-4e0c-b456-d82be49f94f8.png)
It shows the default message ,making me think that it doesnt recognise 'v' command. Used to work in 1.0.0 😞

**Comment by glappy-py** [comment]
Hey there ! Thanks for the feedback, the issue is fixed.

Please update your SpideyCLI using 'spideyupdate' command.

**Comment by Reckadon** [comment]
I updated it, still it is the same 
![image](https://user-images.githubusercontent.com/69901221/141277618-356d563c-e960-49f3-88c6-0c32fcb6f585.png)
